try {
    let objeto = {};
    console.log(objeto.c.a);

} catch(error){
    console.log(`Error: ${error}`)

}finally {
    console.log('finally');
}
z